### ISSUE TITLE
command line import moving not copying

### ISSUE THREAD

**Issue by dmtalon** [photoprism/photoprism-docs#103]
I read somewhere (here I believe) that said for import, copy is the default, however when I run the import command below, it moves files from the import directory.  I tried using --help but it doesn't supply additional options to trigger copy vs. move but indicates it moves files.

I am using the command:  docker exec <docker container> photoprism import
I tried --help and it says that it 'moves'  media files to originals.

Is there a flag to copy?

My use case is, that I am uploading photos via the NextCloud app to the NextCloud Photo directory which is set as the import directory. Unfortunately, this does not auto-trigger importing, so I plan to run a cron task to trigger the above command.  I would like the option to leave the photos within nextcloud also.

**Comment by lastzero** [comment]
Depends on your settings in the UI

**Comment by dmtalon** [comment]
Thank you for the reply. If I use 'copy' will that trigger indexing of the newly copied photos?  Because that is my 'sticky' point right now. Getting Nextcloud synced photos to 'automatically' be introduced into photoprism.  (copied from import, and indexed).

**Comment by lastzero** [comment]
It should
