### ISSUE TITLE
PhotoPrism as Target in PhotoSync only for iOS?

### ISSUE THREAD

**Issue by eifinger** [photoprism/photoprism-docs#104]
I just bought and installed the full version of PhotoSync for Android and tried to follow the directions under https://docs.photoprism.app/user-guide/sync/mobile-devices/#photosync

I don't have Photoprism with its logo as a target as shown in the pictures.

I don't have Backblaze and Wasabi either but they are shown as options in the pictures too. As these two are [iOS only](https://www.photosync-app.com/premium.html#amazons3) I suspect that the PhotoPrism target is iOS only too.

I don't have an iOS device too confirm this but if this is indeed the case I would also be happy to provide a PR for the documentation.
Just want to be sure its not me being silly.

**Comment by eifinger** [comment]
![Screenshot_20220215-094530_PhotoSync](https://user-images.githubusercontent.com/1481961/154025397-59696975-f1b3-43a1-aa2d-be527d0cb2fc.jpg)

**Comment by graciousgrey** [comment]
We already have an info box in the docs

>If you are using PhotoSync on Android you need to choose WebDAV as target.

If you like you can add screenshots from Android to the docs :)

**Comment by eifinger** [comment]
As I assumed it was me being silly^^

Thank you for the fast answer and I will open a PR with a screenshot suggestion
