### ISSUE TITLE
panic: photo label: label is nil

### ISSUE THREAD

**Issue by ChrisFab16** [photoprism/photoprism-docs#12]
Version: PhotoPrism version 200505-bc69f22-Linux-x86_64
Running in docker

running "photoprism index" inside the container yields the following error:

panic: photo label: label is nil

goroutine 41 [running]:
github.com/photoprism/photoprism/internal/entity.(*PhotoLabel).ClassifyLabel(...)
	/go/src/github.com/photoprism/photoprism/internal/entity/photo_label.go:47
github.com/photoprism/photoprism/internal/entity.(*Photo).ClassifyLabels(0xc000daac00, 0xc000c60a20, 0x4, 0x4)
	/go/src/github.com/photoprism/photoprism/internal/entity/photo.go:141 +0x34c
github.com/photoprism/photoprism/internal/photoprism.(*Index).MediaFile(0xc000e7b890, 0xc000fda000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/index_mediafile.go:338 +0x189e
github.com/photoprism/photoprism/internal/photoprism.IndexWorker(0xc00004aae0)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/index_worker.go:23 +0x5ef
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start.func1(0xc00004aae0, 0xc005788d30)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:86 +0x2b
created by github.com/photoprism/photoprism/internal/photoprism.(*Index).Start
	/go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:85 +0x1dc

**Comment by lastzero** [comment]
Thanks for reporting this... should be in our main issue tracker at https://github.com/photoprism/photoprism/issues, but I found it :)

That error should never happen, I'll take a look at it. Any specific image that's causing it?

**Comment by ChrisFab16** [comment]
This photo is where it breaks (the last one to show up in the log before above message)
![IMG_1449](https://user-images.githubusercontent.com/20229082/81165081-af29bf00-8f91-11ea-8147-0e3e00261f83.JPG)

**Comment by lastzero** [comment]
Seems to work for me with our latest Docker image - can you test it again?

![Screenshot 2020-05-15 at 18 57 37](https://user-images.githubusercontent.com/301686/82076320-f9bbe180-96dd-11ea-95aa-c4c8442eb01c.png)

**Comment by ChrisFab16** [comment]
Verified - works in the latest version
