### ISSUE TITLE
Default Docker password broken

### ISSUE THREAD

**Issue by bobobo1618** [photoprism/photoprism-docs#13]
I followed the instructions [here](https://docs.photoprism.org/getting-started/docker/) but wasn't able to log in.

When I added `-e PHOTOPRISM_ADMIN_PASSWORD=<my password>` to my `docker run` command line, I was able to log in.

So I believe the default password is either different or not working.

**Comment by lastzero** [comment]
Yes, that's true. You can now change the password in the UI. So there is no static default in the config anymore. Need to update the docs.
