### ISSUE TITLE
Photosync documentation out of date

### ISSUE THREAD

**Issue by ghigo** [photoprism/photoprism-docs#140]
Docs about master/docs/user-guide/sync)/mobile-devices.md is out of date. PhotoSync Android doesn't show the PP option in their targets

**Comment by lastzero** [comment]
It never did, we are waiting for that to be implemented. You can use WebDAV instead. Merry Christmas!

**Comment by graciousgrey** [comment]
PhotoPrism has recently been added as target in the Android app as well.
