### ISSUE TITLE
Add new cloud deployment method [Elestio]

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [photoprism/photoprism-docs#165]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Photoprism application [as shown here](https://elest.io/open-source/photoprism). I think it would be a great idea if we can add it to official readme/documentation here.
In addition to this, if you are interested we provide collaboration opportunities with tools we support by revenue share upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

<img width="1429" alt="image" src="https://github.com/photoprism/photoprism-docs/assets/53310847/95f44287-295a-4b9c-b226-21d2135f6d79">

**Comment by graciousgrey** [comment]
Thank you very much for your contribution! Unfortunately, we can't merge it at this time, as we only officially recommend cloud solutions that are fully supported and tested by us. We will be happy to consider elestio as a potential partner and get back to you by email as soon as our time allows.
