### ISSUE TITLE
Broken link on Funding page

### ISSUE THREAD

**Issue by navjotjsingh** [photoprism/photoprism-docs#25]
Link to Tiers ( https://github.com/sponsors/lastzero/dashboard/tiers ) is broken on the Funding Page ( https://docs.photoprism.org/funding/ ).

**Comment by lastzero** [comment]
Thanks, should remove this as tiers are shown on main GitHub Sponsors page already.

**Comment by navjotjsingh** [comment]
Seems fixed.
