### ISSUE TITLE
Repository link is broken

### ISSUE THREAD

**Issue by navjotjsingh** [photoprism/photoprism-docs#26]
The link https://docs.photoprism.org/en/latest/ returns 404.

**Comment by lastzero** [comment]
We no longer use the prefix `/en/latest`. Is it fixed now (please reload)?

**Comment by navjotjsingh** [comment]
Truth be told, I was referring to the link shown under About Section here on the repository homepage. Anyway, they are fixed on the funding page.

**Comment by lastzero** [comment]
Good catch! Thanks, fixed 👍
