### ISSUE TITLE
Replace images hosted on Twitter

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism-docs#28]
Some images are provided by Twitter: https://github.com/photoprism/photoprism-docs/search?q=twimg

These images are blocked by Firefox when using the [Strict Enhanced Tracking Protection](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_strict-enhanced-tracking-protection) from Firefox.

So instead of images, we see white rectangle or nothing.

These images should be hosted elsewhere. Ideally on the same server than the doc to avoid depending on an external resource.

Example on https://docs.photoprism.org/developer-guide/metadata/classification/ :

> ![image](https://user-images.githubusercontent.com/2071331/99745052-2ca1c080-2ad9-11eb-833a-41540af1b578.png)

**Comment by lastzero** [comment]
True. Only affects the developer guide though?

**Comment by alexislefebvre** [comment]
This page is affected too: https://docs.photoprism.org/user-guide/settings/library/

**Comment by graciousgrey** [comment]
Should be fixed now, let me know in case I forgot one.

**Comment by alexislefebvre** [comment]
It looks loke it's not deployed as for now.

**Comment by graciousgrey** [comment]
True, I forgot to deploy - now it is ;)

**Comment by alexislefebvre** [comment]
Nice, I can see images now. Thanks!
