### ISSUE TITLE
I made a freebsd port for photoprism

### ISSUE THREAD

**Issue by huo-ju** [photoprism/photoprism-docs#43]
https://github.com/huo-ju/photoprism-freebsd-port

Many users want to using PhotoPrism on FreeBSD/FreeNAS, and I made a port to help them compile the source and install it on FreeBSD. For example [#101 ](https://github.com/photoprism/photoprism/issues/101)  [#333](https://github.com/photoprism/photoprism/issues/333)

It still needs more polishing before being submitted to the main official ports tree, but it works well on my server.  

I'm not sure if it OK to add it to the setup instructions?

**Comment by lastzero** [comment]
Awesome! Maybe in the Advanced section until it's fully stable?

**Comment by huo-ju** [comment]
Prefect, I will send a PR later.

**Comment by fmunteanu** [comment]
@huo-ju any updated on the port creation? Thank you for your work.

**Comment by huo-ju** [comment]
@fmunteanu Yes, I still maintain this port, although may not keep update on each release.
