### ISSUE TITLE
Duplicate FAQ pages

### ISSUE THREAD

**Issue by benmccann** [photoprism/photoprism-docs#50]
I Googled 'photoprism faq' and wasn't able to find the page I was looking for. It turns out there's four different FAQ pages:

* https://docs.photoprism.org/getting-started/faq/
* https://docs.photoprism.org/user-guide/faq/
* https://docs.photoprism.org/user-guide/user-faq/
* https://docs.photoprism.org/faq/faq/

**Comment by lastzero** [comment]
Thanks! Excellent catch... these are drafts we didn't remove from the repo, assuming no one finds them 😂

**Comment by graciousgrey** [comment]
I removed the ones we don't use
