### ISSUE TITLE
Document hardware video transcoding options for the Raspberry Pi

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism-docs#61]
See:

- https://github.com/photoprism/photoprism/issues/703
- https://github.com/photoprism/photoprism/issues/703#issuecomment-780922651
- https://dl.photoprism.org/docker/arm64/docker-compose.yml

CC: @inthreedee @uxusoft @JackyRen @JamesSwift

**Comment by graciousgrey** [comment]
:point_right: https://docs.photoprism.app/getting-started/advanced/transcoding/#raspberry-pi
