### ISSUE TITLE
The “Commands” page has no content

### ISSUE THREAD

**Issue by alexislefebvre** [photoprism/photoprism-docs#71]
See here: https://docs.photoprism.org/user-guide/advanced/commands/

What I see:

> ![image](https://user-images.githubusercontent.com/2071331/114177532-cd840180-993c-11eb-9672-c41219e0af40.png)

There should be content: https://github.com/photoprism/photoprism-docs/blob/master/docs/user-guide/advanced/commands.md

**Comment by graciousgrey** [comment]
Good catch, the whole user-guide/advanced section is not finished yet. That's why its not yet included in the navigation :)

**Comment by alexislefebvre** [comment]
Ok, it will be added to the navigation when it will be ready.
