### ISSUE TITLE
Documentation : MariaDB user creation and privileges grant

### ISSUE THREAD

**Issue by teimahu** [photoprism/photoprism-docs#75]
Hi,

I think there is a mistake with the SQL command for granting rights to the newly created user in file : docs/getting-started/advanced/databases.md

On my setup (MariaDB 10.4.18), I had to change the grant line from:
GRANT ALL PRIVILEGES ON photoprism.* to 'photoprism'@'%';

To:
GRANT ALL PRIVILEGES ON photoprism.* to 'photoprism'@'%' IDENTIFIED BY 'insecure';

And I would end with a:
FLUSH PRIVILEGES;

So that new grant is taken into account.

Thanks,
Mathieu

**Comment by lastzero** [comment]
Updated our docs. Does this work for you?

```sql
CREATE USER 'photoprism'@'%' IDENTIFIED BY 'insecure';
GRANT ALL PRIVILEGES ON photoprism.* to 'photoprism'@'%';
FLUSH PRIVILEGES;
```

Setting the password again with `GRANT ALL` should not be needed IMO.

**Comment by teimahu** [comment]
Yes you are right, I found tutorials with and without it yesterday.
But the MariaDB documentation clearly states that setting the password in GRANT ALL is optionnal, 
I just tested again today creating a new user on my setup and of course, the "identified by" statement is not mandatory, I surely made a mistake yesterday.
Sorry I should have double checked before creating an issue.
